spring.application.name=candle-business

# Serverio nustatymai
server.port=8080
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true

# MySQL duombazės prisijungimas
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/candle_business?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Europe/Vilnius}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=oyesgtl857
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA ir Hibernate nustatymai
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# Thymeleaf koduotė
spring.thymeleaf.encoding=UTF-8

# Naudinga vystymo metu, kad klaidos būtų aiškesnės
server.error.include-message=always
server.error.include-binding-errors=always
